### ISSUE TITLE
Import a Wallet failed

### ISSUE THREAD

**Issue by SiriusLightning21** [remcoros/wasabi-webtop-startos#9]
I uploaded my wallet named "Hot Wallet.json" from Linux Mint. This failed with error can´t load configs file.
For fixing the error I just rename the wallet to "Wallet.json" the error is might be from the spacebar between "Hot Wallet".

**Comment by remcoros** [comment]
I'm seeing this too. Can you test an export/import on your linux mint machine? Maybe it's a bug in Wasabi, but I don't have a linux desktop to test this.

![image](https://github.com/user-attachments/assets/2bb7de9c-7509-47d9-9207-67e248b99047)

**Comment by SiriusLightning21** [comment]
I checked it with Mint and had the same Bug😅
Wasabi don´t like spacebars.

**Comment by remcoros** [comment]
Yea, I was just writing I got this on windows too. I'll submit a fix to wasabi repo.

**Comment by remcoros** [comment]
https://github.com/WalletWasabi/WalletWasabi/issues/13475
